services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: False
      SECRET_KEY: profile-site
      CAPTCHA_SECRET_KEY: ${CAPTCHA_SECRET_KEY}
      CAPTCHA_SITE_KEY: ${CAPTCHA_SITE_KEY}
      SMTP_KEY: ${SMTP_KEY}